#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///
"""Write score-v10.score, the film's score for the v7 cut, from one template.

    uv run film/pipeline/music/v7/make_scores.py

The score's text lives in the template below and in the .inc files it includes; the numbers
that set its levels (the mastering rides) are worked out here. Then run kills.py, which places
HERO's kills on the score's grid (it reads the score's tempo map), and render the score.
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent

TEMPLATE = '''# quake-srp: the film's score, {name}, on edit/{clock}'s clock: {order}. D2 = 72 Hz.
# Generated by v7/make_scores.py: edit that, not this file.
#
# The build: one layer per switch, each switch's bell a step higher and in its breath; the peaks
# climb TORCHES < BURST < ALL ON; ALL ON ends with a button on HERO's out cut. Guitar-free but for
# guitar2 in HERO's action half (its own stem). Silences: the black diff, LAB9, the WASD gag, and
# the Shambler (from S60's cut).
#
#   uv run film/pipeline/music/v7/fit_events.py -o film/pipeline/music/v7/events-{clock}.inc
#   uv run film/pipeline/music/v7/make_scores.py
#   uv run film/pipeline/music/v7/kills.py
#   uv run film/pipeline/music/synth/render.py film/pipeline/music/score-{name}.score --stems

include v7/events-{clock}.inc
let LAYERS_END = {layers_end}
let WARM_END = {warm_end}
let REST_BAND = {rest_band}
let REST_CRASH = {rest_crash}

title    quake-srp score {name}
seeds    stable
tuning   D2=72
length   $END
fadeout  {fadeout}
loudness {loudness}
ceiling  -1

reverb hall t60=5.0 damp=0.28 predelay=0.035
reverb room t60=0.8 damp=0.55

include v7/tracks.inc
include v7/patterns.inc

section @0            M1-corridor
section @$T_M2        M2-the-idea
section @$T_M3        M3-proof
section @$CLASSIC     M4-classic
section @$TORCHES_HIT M4-torches
section @$BURST       M4-burst
section @$PER1        M4-span
section @$HERO        M4-ALL-ON
section @$REST        M4-the-rest
section @$BUILT       M5-fleet
section @$FINALE      M6-closing

include v7/m1-m2.inc
include v7/m3.inc
include v7/m4a-build.inc
include v7/m4-rest.inc
include v7/m4-span-hero.inc
include v7/{m56}.inc
{extra}
# the mastering rides (linear: the stems follow)
auto master level @0 -5.5 @$T_M1_SILENCE -5.5 @$T_TITLE-0.01 -8 @$T_M2-0.5 -8 @$T_M2+1 -2 @$T_M3-1 -2 @$T_M3+1 0
auto master level @$TORCHES_HIT-0.01 0 @$TORCHES_HIT {torches} @$TORCHES_END {torches} @$TORCHES_END+0.3 -2 @$BURST-0.01 -2
auto master level @$BURST {burst} @$BURST+2.0 {burst} @$BURST+2.6 {after_burst} @$HUD {after_burst} @$HUD+2 {hud} @$MIXER {hud}
{rides}
auto master level @$SHAMBLER_OUT-0.01 0 @$FINALE-0.01 0 @$FINALE {finale} @$S63 {finale} {finale_tail}

# the voice's pocket: 250 Hz-4 kHz down under the narration; open on every switch, in its breath
auto master pocket @0 0 @$T_M1_MOTIF-0.5 0 @$T_M1_MOTIF 5 @$T_M1_SILENCE 5 @$T_M1_SILENCE+0.01 0
auto master pocket @$T_M2-0.01 0 @$T_M2+0.5 5 {wipe_pocket}@$BD2_BLACK 5 @$BD2_BLACK+0.01 0 @$BD2_END 0 @$BD2_END+0.3 5
auto master pocket @$ALL_PASS-0.05 5 @$ALL_PASS 0 @$CLASSIC 0 @$CLASSIC+0.5 5
auto master pocket @$TORCHES_HIT-0.05 5 @$TORCHES_HIT 0 @$TORCHES_END 0 @$TORCHES_END+0.3 5
auto master pocket @$WARM_BREATH-0.05 5 @$WARM_BREATH 0 @$WARM_BREATH+1.4 0 @$WARM_BREATH+1.6 5
auto master pocket @$GLIDE_ON-0.05 5 @$GLIDE_ON 0 @$GLIDE_ON+1.0 0 @$GLIDE_ON+1.2 5
auto master pocket @$SMOOTH_MON-0.05 5 @$SMOOTH_MON 0 @$SMOOTH_ON+1.0 0 @$SMOOTH_ON+1.2 5
auto master pocket @$FRAMECAP_ON-0.05 5 @$FRAMECAP_ON 0 @$FRAMECAP_ON+1.0 0 @$FRAMECAP_ON+1.2 5
auto master pocket @$SKY_ON-0.05 5 @$SKY_ON 0 @$SKY_ON+1.0 0 @$SKY_ON+1.2 5
auto master pocket @$BURST-0.05 5 @$BURST 0 @$BURST_END+0.7 0 @$BURST_END+0.9 5
auto master pocket @$NAIL_ON-0.05 5 @$NAIL_ON 0 @$NAIL_ON+0.8 0 @$NAIL_ON+1.0 5
auto master pocket @$SPAN8_ON-0.05 5 @$SPAN8_ON 0 @$SPAN8_ON+0.6 0 @$SPAN8_ON+0.8 5
auto master pocket @$HERO-0.05 5 @$HERO 0 @$ALL_ON_OUT 0 @$ALL_ON_OUT+0.4 5
auto master pocket @$SHAMBLER_OUT 5 @$SHAMBLER_OUT+0.01 0 @$FINALE-0.01 0 @$FINALE+0.5 5 {pocket_end}

# the hits, reported in score-{name}.json
hit @$T_BLAST grenade-blast
hit @$T_TITLE title
hit @$BD1_MERGE BD1-unison
hit @$BD2_BLACK BD2-black
hit @$BD2_END BD2-voice
hit @$STANDARD_VIEWS standard-views
hit @$ALL_PASS all-pass
hit @$CLASSIC classic
hit @$TORCHES_HIT TORCHES
hit @$TORCHES_ON torch-flicker
hit @$WARM_BREATH warm-breath
hit @$GLIDE_ON gliding-lights
hit @$SMOOTH_MON smooth-monsters
hit @$SMOOTH_ON smooth-animations
hit @$FRAMECAP_ON frame-rate-cap
hit @$JUMP1 jump1
hit @$SKY_ON fluid-sky
hit @$BURST BURST
hit @$BURST_END widescreen-fov
hit @$SCALED_HUD scaled-2d
hit @$HUD_OVERLAY status-bar-overlay
hit @$CROSSHAIR crosshair
hit @$NAIL_FREEZE nail-freeze
hit @$NAIL_ON nails-from-barrels
hit @$MIXER lab9-silent
hit @$MIXER_CLEAN lab9-out
hit @$REST the-rest
hit @$CODA_VOICE coda-voice
hit @$WASD wasd-silent
hit @$WASD_END wasd-out
hit @$PER1 span
hit @$SPAN8_ON perspective-span-8
hit @$SHRUG shrug
hit @$HERO ALL-ON
hit @$HERO_ACTION hero-action
hit @$ALL_ON_OUT button
hit @$BUILT M5
hit @$MERGE1 merge1
hit @$RULE1 rule1
hit @$SHAMBLER_OUT shambler-out
hit @$FINALE finale
hit @$CHTHON chthon
hit @$OFF_SPAN8 dark-span8
hit @$OFF_TORCHES dark-torch-flicker
hit @$S63 1996
{end_hits}
hit @$END_CARD end-card
'''

# The rides. ALL ON's action half is 5 dB under its first bar, so the downbeat is the act's loudest as heard: the
# build sets the score's gain from section 4.12 (ALL ON) alone, so that lifts the whole score about 2.6 dB in the
# film, and the burst and TORCHES come down by as much.
LIFT = 2.6
CODA = -7        # the coda after HERO's button, to the WASD gag
LOUDNESS = -21   # mastered low: the build sets the score's level from 4.12 anyway, and this way ALL ON is
                 # not held flat by the limiter (at -16 it pinned the downbeat and the action half alike)

V10 = dict(
    name="v10", clock="v7", loudness=LOUDNESS, fadeout=1.5,
    order="the proof enters on the oracle cut; S16's chord carries across the question",
    layers_end="$MIXER", warm_end="$HERO", rest_band="$REST+0.6", rest_crash="$CAP2",
    torches=round(-13.7 - LIFT, 1), burst=round(-7.5 - LIFT - 0.5, 1), after_burst=round(-7.5 - LIFT, 1),
    hud=round(-8.5 - LIFT, 1), finale=-10.5,
    # LAB9's clean hold at full level, then the suck-out before ALL ON (the run-in's riser carries it);
    # ALL ON's first bar 5 dB over its action half; the button; the coda
    rides="auto master level @$MIXER_CLEAN-0.01 -8.5 @$MIXER_CLEAN 0 @$HERO-0.33 0 @$HERO-0.3 -20 @$HERO-0.01 -20\n"
          "auto master level @$HERO -4 @$HERO+1.9 -4 @$HERO+2.4 -9 @$ALL_ON_OUT-0.01 -9 @$ALL_ON_OUT -4 "
          f"@$ALL_ON_OUT+0.55 -4 @$ALL_ON_OUT+0.8 {CODA} @$WASD {CODA} @$WASD_END-0.01 {CODA} @$WASD_END -3 @$SHAMBLER_OUT-0.02 -3",
    extra="include v7/runin.inc\ninclude v7/kills.inc\n",
    wipe_pocket="",
    # the ending: an arrival just after the last line, not a second climax
    m56="m5-m6-end", finale_tail="@$S63+0.5 0 @$ARRIVAL-0.01 0 @$ARRIVAL -5.5 @$END -5.5",
    pocket_end="@$ARRIVAL-0.05 5 @$ARRIVAL 0",
    end_hits="hit @$LINE54_END line-end\nhit @$ARRIVAL arrival",
)


if __name__ == "__main__":
    import argparse
    argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter).parse_args()
    if not (HERE / "kills.inc").exists():
        (HERE / "kills.inc").write_text("# (written by v7/kills.py)\n")
    (HERE.parent / "score-v10.score").write_text(TEMPLATE.format(**V10))
    print("wrote score-v10.score (then: uv run film/pipeline/music/v7/kills.py)")
