//! `config.cfg` — host.c's `Host_WriteConfiguration` and quake.rc's `exec
//! config.cfg`: the settings a session leaves for the next one, as console
//! lines in the game directory.
//!
//! id's writes its key bindings and every archived cvar when the game
//! quits. A page is never told it quits, so the port writes the file as soon
//! as one of its values changes ([`Archived::write_if_changed`], once a
//! frame), and it archives what the page kept across reloads before it had a
//! file system: the video mode, `viewsize` and the Web extras. (Bindings and
//! the other Options cvars are not archived yet — the page never kept them
//! either.) The values are written without id's quotes, because this
//! console splits its lines on whitespace (it has no `COM_Parse`).

use quake_rs::render::{self, WEB_EXTRAS};

use crate::app::APP;
use crate::common;
use crate::host_cmd::execute_console_command;

/// The file's name in the game directory.
pub(crate) const CONFIG_CFG: &str = "config.cfg";

/// The archived settings, as last written (or read).
#[derive(Debug, Clone, Copy, PartialEq)]
pub(crate) struct Archived {
    /// The video mode (`_vid_resolution`, the port's).
    pub(crate) resolution: (usize, usize),
    /// Options > Screen size.
    pub(crate) viewsize: f32,
    /// Options > Web extras.
    pub(crate) extras: render::Extras,
}

impl Archived {
    /// The live values, or `None` before the App exists.
    pub(crate) fn current() -> Option<Archived> {
        APP.with(|c| {
            c.borrow().as_ref().map(|a| Archived {
                resolution: (a.render_w, a.render_h),
                viewsize: a.menu.viewsize(),
                extras: a.menu.extras(),
            })
        })
    }

    /// The file's text: one console line per value, as `Cvar_WriteVariables`
    /// writes them (unquoted, see the module docs).
    pub(crate) fn text(&self) -> String {
        let mut t = String::from("// generated by quake, do not modify\n");
        let (w, h) = self.resolution;
        t.push_str(&format!("_vid_resolution {w}x{h}\n"));
        t.push_str(&format!("viewsize {}\n", crate::host_cmd::cvar_string(self.viewsize)));
        for x in WEB_EXTRAS {
            t.push_str(&format!("{} {}\n", x.cvar, self.extras.get(x.extra) as u8));
        }
        t
    }

    /// `Host_WriteConfiguration` when a value differs from `last` (the file
    /// as last written): write it and remember what was written. A failed
    /// write is tried again on the next change.
    pub(crate) fn write_if_changed(last: &mut Option<Archived>) {
        let Some(now) = Archived::current() else { return };
        if *last == Some(now) {
            return;
        }
        if common::write_file(CONFIG_CFG, now.text().as_bytes()).is_ok() {
            *last = Some(now);
        }
    }
}

/// quake.rc's `exec config.cfg` (`Cmd_Exec_f`): each line of the file through
/// the console, `//` comments skipped. A missing file is not an error (the
/// first session). Returns the settings as the file left them, so the first
/// frame does not write back what was just read.
pub(crate) fn exec_config() -> Option<Archived> {
    let bytes = common::read_file(CONFIG_CFG).ok()?;
    for line in String::from_utf8_lossy(&bytes).lines() {
        let line = line.split("//").next().unwrap_or("").trim();
        if !line.is_empty() {
            execute_console_command(line);
        }
    }
    Archived::current()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::app::{boot, APP};

    #[test]
    fn the_archived_settings_survive_a_session_through_config_cfg() {
        assert_eq!(boot(), 1);
        crate::vid::set_resolution(640, 400);
        crate::host_cmd::execute_console_command("viewsize 80");
        crate::host_cmd::execute_console_command("wasm_showfps 1");
        let mut last = None;
        Archived::write_if_changed(&mut last);
        let text = String::from_utf8(common::read_file(CONFIG_CFG).unwrap()).unwrap();
        assert!(text.contains("_vid_resolution 640x400\n"), "{text}");
        assert!(text.contains("viewsize 80\n"), "{text}");
        assert!(text.contains("wasm_showfps 1\n") && text.contains("wasm_uncapped 0\n"), "{text}");

        // A new session: the defaults, then the file.
        APP.with(|c| *c.borrow_mut() = None);
        assert_eq!(boot(), 1);
        assert_eq!(Archived::current().unwrap().resolution, (960, 600));
        let read = exec_config().expect("the file is there");
        assert_eq!(read, last.unwrap(), "exec restores what was written");
        assert!(read.extras.show_fps && !read.extras.uncapped);
    }

    #[test]
    fn nothing_is_written_until_a_value_changes() {
        assert_eq!(boot(), 1);
        let mut last = Archived::current();
        Archived::write_if_changed(&mut last);
        assert!(common::read_file(CONFIG_CFG).is_err(), "unchanged: no file");
        crate::host_cmd::execute_console_command("viewsize 110");
        Archived::write_if_changed(&mut last);
        assert!(common::read_file(CONFIG_CFG).is_ok());
    }

    #[test]
    fn a_missing_config_is_the_first_session() {
        assert_eq!(boot(), 1);
        assert_eq!(exec_config(), None);
    }
}
